GET http://localhost:9090/api/vehicles

###

###
POST http://localhost:9090/api/vehicles
Content-Type: application/json

{
  "model": "VW Passat",
  "vehicleYear": 2014,
  "mileage": 172000,
  "loadCapacity": 60
}

###
POST http://localhost:9090/api/vehicles
Content-Type: application/json

{
  "model": "VW Golf",
  "vehicleYear": 2020,
  "mileage": 112000,
  "loadCapacity": 55
}

###
POST http://localhost:9090/api/vehicles
Content-Type: application/json

{
  "model": "BMW",
  "vehicleYear": 2020,

  "loadCapacity": 55
}


###
GET http://localhost:9090/api/vehicles/e1/1

###
GET http://localhost:9090/api/vehicles/e2/1

###
GET http://localhost:9090/api/vehicles/e3/1


###
DELETE http://localhost:9090/api/vehicles/1

###
DELETE http://localhost:9090/api/vehicles/2